### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by tansly** [FBDY/bb-gui#63]
### Expected Behavior

Build of `develop` should be passing.

### Actual Behavior

Build of `develop` is failing:
```
> @bbge/gui@0.1.0 test:lint /home/travis/build/FBDY/bb-gui
> eslint . --ext .js,.jsx
AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (/home/travis/build/FBDY/bb-gui/node_modules/eslint/lib/util/report-translator.js:96:9)
    at args (/home/travis/build/FBDY/bb-gui/node_modules/eslint/lib/util/report-translator.js:246:9)
    at Object.report (/home/travis/build/FBDY/bb-gui/node_modules/eslint/lib/linter.js:720:41)
    at reportUndeclaredPropTypes (/home/travis/build/FBDY/bb-gui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:175:17)
    at Program:exit.Object.keys.filter.forEach.component (/home/travis/build/FBDY/bb-gui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:193:11)
    at Array.forEach (<anonymous>)
    at Object.Program:exit (/home/travis/build/FBDY/bb-gui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:192:81)
    at updatedRuleInstructions.(anonymous function) (/home/travis/build/FBDY/bb-gui/node_modules/eslint-plugin-react/lib/util/Components.js:754:75)
    at listeners.(anonymous function).forEach.listener (/home/travis/build/FBDY/bb-gui/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
(node:5938) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "scratch/es6")
```

### Steps to Reproduce

Automated Travis build reproduces it.

**Comment by tansly** [comment]
As far as I can remember, we did not change anything. It was passing then, it's failing now.

**Comment by tansly** [comment]
Found out that upstream `scratch-gui` was getting the same error: [pr4215](https://github.com/LLK/scratch-gui/pull/4215)

`eslint-plugin-react` is the cuplrit.
